### ISSUE TITLE
Unable to fetch the entities on the backend

### ISSUE THREAD

**Issue by nelsonec87** [Kinvey/nativescript-sdk#16]
Hi, I'm just playing around with the groceries example and i'm getting intermittently the following errors:

`KinveyError: An error occurred.`

or

`KinveyError: Unable to fetch the entities on the backend. There are 1 entities that need to be synced.`

When I clear the app's data and reopen the app it works again (for some time).

I don't have the code anymore cause i decided to use the REST directly, just thought you guys should know about this behavior. []

**Comment by thomasconner** [comment]
@nelsonec87 This is fixed with the release of [3.7.2](https://github.com/Kinvey/nativescript-sdk/releases/tag/v3.7.2). Please make sure you also have the correct permissions to update any entities that you are attempting to sync.
