### ISSUE TITLE
Unable to run app after upgrading Xcode to 9.0

### ISSUE THREAD

**Issue by jlooper** [Kinvey/nativescript-sdk#23]
#### Steps to Reproduce
`tns create myApp --ng`
app is built properly
`cd myApp`
`tns plugin add kinvey-nativescript-sdk`
`tns run ios`

#### Expected Result
App should start up as expected as a master/detail app with Kinvey plugin installed

#### Actual Result
Error
```
### Podfile

```ruby
use_frameworks!

target "myKinveyApp" do
# Begin Podfile - /Users/Looper/Desktop/myKinveyApp/node_modules/kinvey-nativescript-sdk/platforms/ios/Podfile 
 platform :ios, '9.0'
pod 'SAMKeychain', '~> 1.5.2'
 
 # End Podfile 

end

### Error
```
more debugging notes:

LoadError - cannot load such file -- nanaimo
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:23:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:855:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:854:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:849:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Looking for related issues on cocoapods/cocoapods...
 - LoadError - cannot load such file -- nanaimo
   https://github.com/CocoaPods/CocoaPods/issues/6214 [closed] [39 comments]
   13 Jun 2017

 - LoadError - cannot load such file -- nanaimo
   https://github.com/CocoaPods/CocoaPods/issues/6281 [closed] [20 comments]
   20 Apr 2017

 - pod lib create fails: uninitialized constant Nanaimo::Reader::StringScanner (NameError)
   https://github.com/CocoaPods/CocoaPods/issues/6106 [closed] [22 comments]
   12 Jun 2017

#### Version of Kinvey NativeScript SDK
3.8.0

#### Kinvey AppKey
n/a
#### NodeJS version
6.9.1

**Comment by tejasranade** [comment]
@jlooper I tried following the same steps after installing XCode 9. I was able to get the app running on iOS 11 simulator and device. 

I wonder if this is a CocoaPods version or similarly related issue. Here is some more info about my environment -

```
CocoaPods version -> 1.2.1
> gem which nanaimo
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo.rb
```

Let me know what you see on yours.

**Comment by jlooper** [comment]
@tejasranade that did it, thank you. Looks like I needed to do a pod update. Thanks, onwards and upwards!
