### ISSUE TITLE
Angular 2 Support

### ISSUE THREAD

**Issue by MartoYankov** [Kinvey/nativescript-sdk#27]
Do you plan on making the sdk fully compatible with Angular 2? Currently, I have to init the kinvey sdk on startup with a script. Normally, Angular should handle app startup with modules. I expect to be able to import a module in my app core module and then inject the kinvey sdk service in a given component through the constructor. See Angularfire for example - https://github.com/angular/angularfire2.

**Comment by thomasconner** [comment]
Yes we do plan to support Angular2+

**Comment by thomasconner** [comment]
@MartoYankov Just wanted to reach out and let you know this is still on our radar.

**Comment by manoldonev** [comment]
Seems this is addressed with version 4.1.x of the plugin now.
