### ISSUE TITLE
Issue compiling kinvey-nativescript-sdk

### ISSUE THREAD

**Issue by AdamShechter9** [Kinvey/nativescript-sdk#30]
installed package using nativescript cli
'tns plugin add kinvey-nativescript-sdk'

Result

=> tns run android
Searching for devices...
Executing before-liveSync hook from /Development/nativescript/Groceries/hooks/before-liveSync/nativescript-angular-sync.js
Executing before-prepare hook from /Development/nativescript/Groceries/hooks/before-prepare/nativescript-dev-android-snapshot.js
Executing before-prepare hook from /Development/nativescript/Groceries/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
node_modules/kinvey-nativescript-sdk/kinvey.d.ts(269,9): error TS2314: Generic type 'CacheStore<T, Entity>' requires 2 type argument(s).

node_modules/kinvey-nativescript-sdk/kinvey.d.ts(274,41): error TS1005: ',' expected.

node_modules/kinvey-nativescript-sdk/kinvey.d.ts(301,39): error TS1005: ',' expected.
node_modules/kinvey-nativescript-sdk/kinvey.d.ts(301,58): error TS2314: Generic type 'NetworkStore<T, Entity>' requires 2 type argument(s).
node_modules/kinvey-nativescript-sdk/kinvey.d.ts(321,38): error TS1005: ',' expected.

node_modules/kinvey-nativescript-sdk/kinvey.d.ts(321,57): error TS2507: Type 'typeof CacheStore' is not a constructor function type.

node_modules/kinvey-nativescript-sdk/kinvey.d.ts(345,34): error TS1005: ',' expected.
node_modules/kinvey-nativescript-sdk/kinvey.d.ts(346,38): error TS1005: ',' expected.
node_modules/kinvey-nativescript-sdk/kinvey.d.ts(347,38): error TS1005: ',' expected.
node_modules/kinvey-nativescript-sdk/kinvey.d.ts(349,36): error TS1005: ',' expected.
node_modules/kinvey-nativescript-sdk/kinvey.d.ts(354,36): error TS1005: ',' expected.

node_modules/kinvey-nativescript-sdk/kinvey.d.ts(785,7): error TS2314: Generic type 'CacheStore<T, Entity>' requires 2 type argument(s).
node_modules/kinvey-nativescript-sdk/kinvey.d.ts(790,45): error TS1005: ',' expected.
node_modules/kinvey-nativescript-sdk/kinvey.d.ts(811,43): error TS1005: ',' expected.
node_modules/kinvey-nativescript-sdk/kinvey.d.ts(811,61): error TS2314: Generic type 'NetworkStore<T, Entity>' requires 2 type argument(s).
node_modules/kinvey-nativescript-sdk/kinvey.d.ts(831,42): error TS1005: ',' expected.

node_modules/kinvey-nativescript-sdk/kinvey.d.ts(831,60): error TS2507: Type 'typeof CacheStore' is not a constructor function type.
node_modules/kinvey-nativescript-sdk/kinvey.d.ts(855,30): error TS1005: ',' expected.

node_modules/kinvey-nativescript-sdk/kinvey.d.ts(856,34): error TS1005: ',' expected.

node_modules/kinvey-nativescript-sdk/kinvey.d.ts(857,34): error TS1005: ',' expected.

node_modules/kinvey-nativescript-sdk/kinvey.d.ts(859,32): error TS1005: ',' expected.

node_modules/kinvey-nativescript-sdk/kinvey.d.ts(864,32): error TS1005: ',' expected.

Unable to apply changes on device: emulator-5554. Error is: TypeScript compiler failed with exit code 1.

All NativeScript components versions information
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 3.4.2           │ 3.4.2          │ Up to date       │
│ tns-core-modules │ 3.0.1           │ 3.4.0          │ Update available │
│ tns-android      │ 3.4.1           │ 3.4.1          │ Up to date       │
│ tns-ios          │                 │ 3.4.1          │ Not installed    │

node 6.10.3

**Comment by thomasconner** [comment]
@AdamShechter9 There appears to be several TypeScript errors that is causing the app to not compile. What version of TypeScript are you using?

**Comment by thomasconner** [comment]
We are using the latest version of TypeScript. I will have to look into the issues.

**Comment by EddyVerbruggen** [comment]
Hi @AdamShechter9, @thomasconner was pointing you in the right direction; your TypeScript version at the time of this error was 2.2.2 (as shown in the log you posted). Bumping this to (for instance) `"~2.7.0"` fixes the compilation issues.
