### ISSUE TITLE
Files upload not reaching Google Cloud

### ISSUE THREAD

**Issue by fmu93** [Kinvey/nativescript-sdk#32]
I have tried copying all demos and templates to my project, it's just not reacting... only I see up to the last console.log() before theKinvey.Files.upload(file, metadata), and on the Kinvey console I see the file name and size, but nothing happens when clicking on it or it says "access denied", presumably that this file does not exist. I'm using typescript without Angular.

I am getting a bit desperate since there aren't even errors or confirmations of the upload. What am I doing wrong?

    static uploadImage(filePathShort: string, fileId: string) {
        const appPath = fs.knownFolders.currentApp();
        const localFullPath = fs.path.join(appPath.path, filePathShort);
        console.log("Trying to upload: " + localFullPath);
        if (!fs.File.exists(localFullPath)) {
            console.log("File does not exist");

            return null;
        }

        const file = fs.File.fromPath(localFullPath);
        const metadata = {
            filename: fileId + file.extension,
            mimeType: "image/png", // TODO format
            size: file.readSync().length,
            public: true
        };
        const promise = Kinvey.Files.upload(file, metadata)
            .then((result: any) => {
            console.log("Uploaded: " + JSON.stringify(result));
            })
            .catch((error: Kinvey.BaseError) => {
            console.log(error);
            });
    }

#### Version of Kinvey NativeScript SDK
"kinvey-nativescript-sdk": "3.9.10",

#### Kinvey AppKey
kinveyAppKey: "kid_HJpLpxsIG"

#### NodeJS version
node -v
v8.9.4

**Comment by thomasconner** [comment]
@fmu93 Thanks for reporting. We are aware of your issue and are looking into it. I will report back once we have an update.

**Comment by andymuldoon22** [comment]
I've been having the same issue, has there been a solution found to this yet?

**Comment by thomasconner** [comment]
@andymuldoon22 No there has not been a solution found to this yet but we are actively looking into the issue. I will update this issue once a solution has been found. Thanks for your patience.

**Comment by thomasconner** [comment]
This issue was resolved with [3.10.2 release](https://github.com/Kinvey/js-sdk/releases/tag/v3.10.2).
