### ISSUE TITLE
Kinvey: Register for push notifications always fails...

### ISSUE THREAD

**Issue by relez** [Kinvey/nativescript-sdk#33]
Hi there, I a trying to register for push notifications using kinvey-nativescript-sdk, I have uploaded the .p12 certificate for push (development) to the Kinvey Console and the following code in my project:

```
Push.register({
    android: {
          senderID: '1234567890'
    },
    ios: {
        badge: true,
        sound: true,
        alert: true,
    }
})
.then((deviceToken: string) => {
    console.log('Registered: ' + deviceToken);
})
.catch((error: Error) => {
    console.log(error.message);
});
```
I have installed `nativescript-push-notifications` plugin and added these lines to the entitlements file:
```
<key>aps-environment</key>
<string>development</string>
```
Is there something I am missing? 

Thanks!

**Comment by thomasconner** [comment]
We updated our `push` module for push notifications in the [latest release(https://github.com/Kinvey/js-sdk/releases/tag/v3.10.3). This should resolve the issue you were having.
