### ISSUE TITLE
File upload on Android fails

### ISSUE THREAD

**Issue by steinerj** [Kinvey/nativescript-sdk#35]
#### Steps to Reproduce
```
this.login().then(() => {
            // Test UL
            const filePath = fs.path.join(fs.knownFolders.currentApp().path, "/julian.jpg");
            const file = fs.File.fromPath(filePath);
            console.log("file ", JSON.stringify(file));
            const metadata = {
                _id: "123456",
                filename: file.name,
                mimeType: "image/jpeg",
                size: file.readSync().length,
                public: true
            };

            Kinvey.Files.upload(file, metadata)
                .then((uploadedFile: any) => {
                    console.log("success ", JSON.stringify(uploadedFile));
                })
                .catch((error: Kinvey.BaseError) => {
                    console.log("kaputt ", error);
                });
        });

```
#### Expected Result
An uploaded image to Kinvey.

#### Actual Result
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ANGULAR BOOTSTRAP DONE. 13877
**JS: file  {"_path":"/data/data/org.nativescript.filetest/files/app/julian.jpg","_name":"julian.jpg","_extension":".jpg"}
JS: kaputt  Error: com.tns.NativeScriptException: Failed to find module: "/./file-upload-worker", relative to: app/tns_modules/kinvey-nativescript-sdk//**

JS:     com.tns.Module.resolvePathHelper(Module.java:146)
JS:     com.tns.Module.resolvePath(Module.java:55)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:957)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:941)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:933)
JS:     com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
JS:     android.os.Handler.handleCallback(Handler.java:733)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:136)
JS:     android.app.ActivityThread.main(ActivityThread.java:5001)
JS:     java.lang.reflect.Method.invokeNative(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:515)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
JS:     dalvik.system.NativeStart.main(Native Method)

#### Versions
kinvey-nativescript-sdk: 3.10.3 (also tested 3.10.2)
NativeScript Android: 3.4.2 & 4.0.1
Andoid API Level: 19 & 23 (tested)

#### Kinvey AppKey
kid_SkDUMhCtM

#### NodeJS version
v9.11.1 on Windows

**Comment by thomasconner** [comment]
This has been fixed with [3.11.1](
https://github.com/Kinvey/nativescript-sdk/releases/tag/v3.11.1) release.
