### ISSUE TITLE
notification error after install kinvey-nativescript-sdk

### ISSUE THREAD

**Issue by mbelaj** [Kinvey/nativescript-sdk#37]
Hi,

I having some problems after installing new sdk version:

CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:1486:24: ERROR Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'kinvey_nativescript_sdk_1.Push.onNotification')

CONSOLE LOG file:///app/views/index/index.component.js:278:24: SOME ERROR : TypeError: undefined is not an object (evaluating 'kinvey_nativescript_sdk_1.Push.register’)

**Comment by thomasconner** [comment]
This has been fixed with [3.11.5](
https://github.com/Kinvey/nativescript-sdk/releases/tag/v3.11.5) release.
