### ISSUE TITLE
Getting push notification data

### ISSUE THREAD

**Issue by finger563** [Kinvey/nativescript-sdk#39]
#### Steps to Reproduce
Register app for push notifications (`Push.register(...)`) and define a callback (`Push.onNotification((data) => { ... } )`)
Send a notification from the kinvey console

#### Expected Result
the `data` passed to `onNotification` callback should have some data in it (possibly including the notification `Message` that was input in the kinvey console?

#### Actual Result
```js
data = {
  "foreground": true
};
```

#### Version of Kinvey NativeScript SDK
3.11.5

**Comment by finger563** [comment]
As a note - this seems to be only on android devices - on iOS devices we get:
```js
{
  "content-available": "0",
  "alert": "Here is a test notification",
  "badge": "",
  "sound": "",
  "foreground": "1"
}
```

which may not be completely correct but is at least better :)

**Comment by finger563** [comment]
Further info: the android notification center does show the correct text for the notification - even though the app does not receive that data.

**Comment by bradmartin** [comment]
@thomasconner - any chance this will be looked at with an upcoming release? 😄

**Comment by thomasconner** [comment]
@bradmartin @finger563  We recently updated our [Push Notification Guide](https://devcenter.kinvey.com/nativescript/guides/push) for NativeScript that describes how to properly format a push notification for NativeScript. This should resolve the issue.

**Comment by bradmartin** [comment]
Thanks @thomasconner 😄 ❤️
