### ISSUE TITLE
Webpack cannot build kinvey "Parsed request is a module"

### ISSUE THREAD

**Issue by IAMtheIAM** [Kinvey/nativescript-sdk#40]
I imported like normal and am getting a weird error message. 
```
import { Kinvey } from "kinvey-nativescript-sdk";

Kinvey.init({
    apiHostname: 'CUSTDEP_HOST',
    micHostname: 'CUSTDEP_MIC_HOST',
    appKey: 'kid_Bk-U_Zfr7',
    appSecret: 'c2292bf9e5a0442985fe25afe23e8dfc'
})
```

#### Actual Result
```
System.err: 
System.err: Error calling module function 
System.err: 
System.err: Error calling module function 
System.err: 
System.err: TypeError: Cannot read property 'init' of undefined
System.err: File: "file:///data/data/edu.a.app/files/app/vendor.js, line: 70507, column: 516290
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'e', file:'file:///data/data/edu.taccd.app/files/app/vendor.js', line: 70507, column: 516291
System.err: 	Frame: function:'push.../node_modules/kinvey-nativescript-sdk/kinvey-nativescript-sdk.js', file:'file:///data/data/edu.a.app/files/app/vendor.js', line: 70507, column: 515252

```

What does it want to be compatible with webpack 4?

#### Version of Kinvey NativeScript SDK

3.11.6

#### NodeJS version

8.11.1

I believe the reason why is because package.json has `main` field points to `kinvey-nativescript-sdk.js` which does not exist. How should webpack know whether to resolve `kinvey-nativescript-sdk.android.js` or `kinvey-nativescript-sdk.ios.js`?

**Comment by EddyVerbruggen** [comment]
Hi, I've tried reproducing the issue with the same plugin version you've used, but can't "break" it. Although I agree with your remark about changing the `main`.

Would you be able to throw the project in a repo so we can try to reproduce your issue?
