### ISSUE TITLE
Logout problem

### ISSUE THREAD

**Issue by baretka** [Kinvey/nativescript-sdk#41]
#### Steps to Reproduce
ERROR TypeError: null is not an object (evaluating 'kinvey_nativescript_sdk_1.Kinvey.User.getActiveUser().data’)
It happends wheni press on logout();

#### Expected Result
Logout

#### Actual Result
It throws error for 30sec and then logout.

#### Sample Code that demonstrates the issue
const promise = Kinvey.User.logout()
      .then(() => {
        this.loader.hide();
        this.routerExtensions.navigate(["authentication"], { clearHistory: true });
      }).catch((error: Kinvey.BaseError) => {
        this.loader.hide();
        console.log("User logout error: " + error);
        let toast = Toast.makeText("Error: " + error).show();
      })

#### Version of Kinvey NativeScript SDK
3.11.4

**Comment by EddyVerbruggen** [comment]
Hi @baretka, I just tried to reproduce this on both iOS and Android and it all worked fine for me. Perhaps you were able to make it work in the meanwhile as well?

I'm using Kinvey SDK 3.11.7 and this is my code:

```typescript
Kinvey.User.login(MY_USERNAME, MY_PASSWORD)
    .then(() => {
      console.log("logged in, will now attempt to log out");

      Kinvey.User.logout()
          .then(() => console.log("logged out"))
          .catch((error: Kinvey.BaseError) => console.log("log out error: " + error));
    });
```

If you can't make it work, please share a repo demonstrating the issue and I'll gladly take a look.
