### ISSUE TITLE
Push.unregister throws Invalid Project ID error

### ISSUE THREAD

**Issue by bradmartin** [Kinvey/nativescript-sdk#44]
Kinvey SDK: 3.11.6

`Push.unregister` throws error `Invalid Project ID`.

I'm able to register fine with the configuration I have, push messages work fine, but am unable to unregister successfully. Looked over docs and don't see mention of passing any args to `unregister`.

**Comment by ramoncardena** [comment]
Same problem here. 

> "dependencies": {
>     "@angular/animations": "~6.1.0",
>     "@angular/common": "~6.1.0",
>     "@angular/compiler": "~6.1.0",
>     "@angular/core": "~6.1.0",
>     "@angular/forms": "~6.1.0",
>     "@angular/http": "~6.1.0",
>     "@angular/platform-browser": "~6.1.0",
>     "@angular/platform-browser-dynamic": "~6.1.0",
>     "@angular/router": "~6.1.0",
>     "kinvey-nativescript-sdk": "^3.11.6",
>     "nativescript-angular": "^6.1.0",
>     "nativescript-camera": "^4.0.2",
>     "nativescript-filterable-listpicker": "^2.1.0",
>     "nativescript-imagepicker": "^6.0.3",
>     "nativescript-iqkeyboardmanager": "^1.3.0",
>     "nativescript-localize": "^3.0.3",
>     "nativescript-modal-datetimepicker": "^1.1.4",
>     "nativescript-phone": "^1.3.1",
>     "nativescript-push-notifications": "^1.1.5",
>     "nativescript-theme-core": "~1.0.4",
>     "nativescript-ui-dataform": "^3.6.1",
>     "nativescript-ui-listview": "^3.5.5",
>     "reflect-metadata": "~0.1.10",
>     "rxjs": "^6.3.1",
>     "tns-core-modules": "^4.2.0",
>     "zone.js": "^0.8.26"
>   }

**Comment by bradmartin** [comment]
@ramoncardena pass and `android:` object into the unregister and it should work. At least that's what I'm doing, it's not typed that way right now so you can bypass with `any` on the Push module if the TS warning bothers you for now. Again, I think Thomas knows about this from a discussion last week.

**Comment by ramoncardena** [comment]
Thanks @bradmartin, it worked adding the object into unregister.

**Comment by thomasconner** [comment]
@ramoncardena and @bradmartin We released 3.12.0 yesterday contains an update to the TypeScript definitions for Push that allows options to be passed to `unregister()`. The same options format that is provided to `register()` should be provided to `unregister()`.
