### ISSUE TITLE
Push notification deprecated

### ISSUE THREAD

**Issue by bradmartin** [Kinvey/nativescript-sdk#47]
With the push plugin being deprecated in favor of firebase push for NS (https://github.com/NativeScript/push-plugin#push-plugin-for-nativescript), is there a plan to update the SDK so we don't need to keep using the deprecated plugin?

**Comment by elena-p** [comment]
@thomasconner, here is the migration guide from push plugin to firebase plugin https://github.com/NativeScript/push-plugin/blob/master/MIGRATE-TO-FIREBASE.md
