### ISSUE TITLE
Issue with gradlew

### ISSUE THREAD

**Issue by EcDaDev** [Kinvey/nativescript-sdk#51]
#### Steps to Reproduce
- Running under Ubuntu 16.04,
- NodeJS 10.15.3,
- Vue 3.7.0,
- Android Studio 3.4.1,
    - Build #AI-183.6156.11.34.5522156, built on May 1, 2019,
    - JRE: 1.8.0_152-release-1343-b16-5323222 amd64,
    - JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o,
    - Linux 4.4.0-146-generic.
- Download this project: https://play.nativescript.org/?template=play-vue&id=7YrUzj&v=7
- Execute: `tns install` then `tns build android --bundle`

#### Expected Result
Successful apk build.

#### Actual Result
```
Failed to build plugin kinvey-nativescript-sdk : 
Error: spawn ./gradlew EACCES
```

##### Here is the same issue:
https://stackoverflow.com/questions/56251418/issue-with-gradlew-in-nativescript-tns-run-and-tns-build

**Comment by thomasconner** [comment]
Hey @EcDaDev are you still having this issue?

**Comment by EcDaDev** [comment]
Hi @thomasconner, no, for now it is OK.
Guys here helped me a bit:
https://stackoverflow.com/questions/56251418/issue-with-gradlew-in-nativescript-tns-run-and-tns-build

**Comment by EcDaDev** [comment]
Sorry for late reply, you can close the ticket.
