### ISSUE TITLE
Searching for removed 'nativescript-push-notifications' ?

### ISSUE THREAD

**Issue by ADjenkov** [Kinvey/nativescript-sdk#8]
Hi, 

I'm getting  `Failed to find module:"nativescript-push-notifications" relative to: app/tns_modules` exception when run {N} 3.0.1 Angular 2  Android app with the plugin installed.

I see that you've removed the push-notifications dependency some commits ago, but I think that `nativescript-sdk/src/push/` files are still depending on it ?

Using  "kinvey-nativescript-sdk": "3.6.0-ns.5"

**Comment by tejasranade** [comment]
@ADjenkov thanks for reporting. We're looking into it now. 
Does installing the `nativescript-push-notifications` plugin separately fix the issue for you?

**Comment by ADjenkov** [comment]
Thanks for the fast reply.
Unfortunately I won't be able to test it right now.

**Comment by ADjenkov** [comment]
@tejasranade Yes it does. When I've installed `nativescript-push-notifications` separately all went well. Is the plugin going to depend on `nativescript-push-notifications` in the future? 

_I'm asking this because there is something I'm trying to figure out right now related to the required `google-service.json` file (which won't be needed if this dependency is removed)._
